"""Export all database models for SQLAlchemy metadata registration."""

from app.db.base import Base, TimestampMixin
from app.models.source import SourceDocument, SourceType, DataClassification
from app.models.company import Company, Security
from app.models.financial_period import FinancialPeriod, PeriodType, ReportingStandard, FinancialUnit
from app.models.financial_statements import (
    IncomeStatement,
    BalanceSheet,
    CashFlowStatement,
    StatementType,
)
from app.models.corporate_actions import CorporateAction, ActionType, ShareCountHistory
from app.models.provenance import DataProvenance
from app.models.validation import ValidationResult, ValidationStatus, ValidationCategory
from app.models.fundamental_analysis import FundamentalMetricRecord
from app.models.forensic import (
    ForensicRiskLevel,
    SignalCategory,
    ForensicSignal,
    BeneishVariable,
    BeneishMScoreResult,
    PiotroskiSignal,
    PiotroskiFScoreResult,
    AltmanZScoreResult,
    PeriodForensicScorecard,
    CompanyForensicResponse,
)

from app.models.valuation import (
    ValuationMethod,
    TerminalValueMethod,
    ScenarioType,
    CashFlowProjectionYear,
    WACCBreakdown,
    TerminalValueDiagnostics,
    DCFValuationInputs,
    DCFValuationResult,
    ReverseDCFInputs,
    ReverseDCFResult,
    MultipleMetricComparison,
    MultiplesValuationResult,
    ScenarioCase,
    ScenarioAnalysisResult,
    SensitivityCell,
    SensitivityMatrixResult,
    BankDDMYear,
    BankValuationResult,
    SOTPSegment,
    SOTPValuationResult,
    ValuationSummaryResponse,
)

from app.models.document_intelligence import (
    DocumentType,
    DocumentProcessingStatus,
    DocumentRecord,
    DocumentPageRecord,
    DocumentChunkRecord,
    DocumentPageDTO,
    DocumentMetadataDTO,
    DocumentDetailDTO,
    EvidenceCitation,
    DocumentRetrievalQuery,
    DocumentRetrievalResult,
    DocumentRetrievalResponse,
    IngestionUploadResponse,
)

from app.models.ai_analyst import (
    QuestionIntent,
    ClaimGroundingStatus,
    GuidanceCategory,
    DeliveryStatus,
    WatchlistAlertSeverity,
    WatchlistRecord,
    ManagementGuidanceRecord,
    AnalyticalClaim,
    AIAnalystQuery,
    AIAnalystResponse,
    ManagementSaidVsDidItem,
    ManagementSaidVsDidResponse,
    PointInTimeAnalysisRequest,
    PointInTimeAnalysisResponse,
    WatchlistAlert,
    WatchlistItemDTO,
    CompanyResearchReport,
)

__all__ = [
    "Base",
    "TimestampMixin",
    "SourceDocument",
    "SourceType",
    "DataClassification",
    "Company",
    "Security",
    "FinancialPeriod",
    "PeriodType",
    "ReportingStandard",
    "FinancialUnit",
    "IncomeStatement",
    "BalanceSheet",
    "CashFlowStatement",
    "StatementType",
    "CorporateAction",
    "ActionType",
    "ShareCountHistory",
    "DataProvenance",
    "ValidationResult",
    "ValidationStatus",
    "ValidationCategory",
    "FundamentalMetricRecord",
    "ForensicRiskLevel",
    "SignalCategory",
    "ForensicSignal",
    "BeneishVariable",
    "BeneishMScoreResult",
    "PiotroskiSignal",
    "PiotroskiFScoreResult",
    "AltmanZScoreResult",
    "PeriodForensicScorecard",
    "CompanyForensicResponse",
    "ValuationMethod",
    "TerminalValueMethod",
    "ScenarioType",
    "CashFlowProjectionYear",
    "WACCBreakdown",
    "TerminalValueDiagnostics",
    "DCFValuationInputs",
    "DCFValuationResult",
    "ReverseDCFInputs",
    "ReverseDCFResult",
    "MultipleMetricComparison",
    "MultiplesValuationResult",
    "ScenarioCase",
    "ScenarioAnalysisResult",
    "SensitivityCell",
    "SensitivityMatrixResult",
    "BankDDMYear",
    "BankValuationResult",
    "SOTPSegment",
    "SOTPValuationResult",
    "ValuationSummaryResponse",
    "DocumentType",
    "DocumentProcessingStatus",
    "DocumentRecord",
    "DocumentPageRecord",
    "DocumentChunkRecord",
    "DocumentPageDTO",
    "DocumentMetadataDTO",
    "DocumentDetailDTO",
    "EvidenceCitation",
    "DocumentRetrievalQuery",
    "DocumentRetrievalResult",
    "DocumentRetrievalResponse",
    "IngestionUploadResponse",
    "QuestionIntent",
    "ClaimGroundingStatus",
    "GuidanceCategory",
    "DeliveryStatus",
    "WatchlistAlertSeverity",
    "WatchlistRecord",
    "ManagementGuidanceRecord",
    "AnalyticalClaim",
    "AIAnalystQuery",
    "AIAnalystResponse",
    "ManagementSaidVsDidItem",
    "ManagementSaidVsDidResponse",
    "PointInTimeAnalysisRequest",
    "PointInTimeAnalysisResponse",
    "WatchlistAlert",
    "WatchlistItemDTO",
    "CompanyResearchReport",
]


