"""Base interfaces and constants for Document Intelligence & RAG subsystem."""

RAG_METHODOLOGY_VERSION = "v1.0.0-phase6"

# Canonical Indian Statutory Annual Report Sections
INDIAN_ANNUAL_REPORT_SECTIONS = [
    "DIRECTORS_REPORT",
    "MANAGEMENT_DISCUSSION_AND_ANALYSIS",
    "BUSINESS_RESPONSIBILITY_AND_SUSTAINABILITY",
    "CORPORATE_GOVERNANCE_REPORT",
    "INDEPENDENT_AUDITORS_REPORT",
    "CONSOLIDATED_BALANCE_SHEET",
    "CONSOLIDATED_STATEMENT_OF_PROFIT_AND_LOSS",
    "CONSOLIDATED_CASH_FLOW_STATEMENT",
    "NOTES_TO_CONSOLIDATED_FINANCIAL_STATEMENTS",
    "STANDALONE_FINANCIAL_STATEMENTS",
    "RELATED_PARTY_DISCLOSURES",
    "RISK_MANAGEMENT_AND_INTERNAL_CONTROLS",
    "GENERAL_CORPORATE_INFORMATION",
]
