"""create_phase_1_financial_data_tables

Revision ID: d3664697577f
Revises: 
Create Date: 2026-10-02 19:40:23.380255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3664697577f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('primary_exchange', sa.String(length=10), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('registered_state', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cin'), 'companies', ['cin'], unique=True)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=True)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('NSE_FILING', 'BSE_FILING', 'MCA_XBRL', 'RBI_DBIE', 'ANNUAL_REPORT_PDF', 'PRESS_RELEASE', 'AUDITED_FINANCIALS_FIXTURE', 'MOCK_FIXTURE', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('data_classification', sa.Enum('REAL', 'SYNTHETIC', 'MOCK', 'DERIVED', name='dataclassification', native_enum=False), nullable=False),
    sa.Column('file_path_or_url', sa.String(length=500), nullable=True),
    sa.Column('retrieval_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('terms_and_license', sa.Text(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('attribution_notes', sa.Text(), nullable=True),
    sa.Column('raw_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('BALANCE_SHEET_RECONCILIATION', 'CASH_FLOW_RECONCILIATION', 'INCOME_STATEMENT_MATH', 'PERIOD_CONSISTENCY', 'HISTORICAL_ORDERING', 'DUPLICATE_CHECK', 'UNIT_AND_CURRENCY', 'CONSOLIDATED_STANDALONE_INTEGRITY', 'ANOMALY_DETECTION', name='validationcategory', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'WARNING', name='validationstatus', native_enum=False), nullable=False),
    sa.Column('formula_checked', sa.String(length=255), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('discrepancy', sa.Float(), nullable=True),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_category'), 'validation_results', ['category'], unique=False)
    op.create_index(op.f('ix_validation_results_company_id'), 'validation_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_validation_results_entity_id'), 'validation_results', ['entity_id'], unique=False)
    op.create_index(op.f('ix_validation_results_entity_type'), 'validation_results', ['entity_type'], unique=False)
    op.create_index(op.f('ix_validation_results_period_id'), 'validation_results', ['period_id'], unique=False)
    op.create_index(op.f('ix_validation_results_rule_name'), 'validation_results', ['rule_name'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('STOCK_SPLIT', 'BONUS_ISSUE', 'DIVIDEND', 'RIGHTS_ISSUE', 'BUYBACK', 'FACE_VALUE_CHANGE', name='actiontype', native_enum=False), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ratio_numerator', sa.Float(), nullable=True),
    sa.Column('ratio_denominator', sa.Float(), nullable=True),
    sa.Column('adjustment_factor', sa.Float(), nullable=False),
    sa.Column('dividend_per_share', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_company_id'), 'corporate_actions', ['company_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_table('data_provenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('reported_label', sa.String(length=255), nullable=False),
    sa.Column('reported_value_raw', sa.String(length=100), nullable=False),
    sa.Column('reported_unit', sa.String(length=50), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.Column('normalized_unit', sa.String(length=50), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('table_reference', sa.String(length=255), nullable=True),
    sa.Column('note_reference', sa.String(length=100), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('transformation_applied', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_provenance_entity_id'), 'data_provenance', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_provenance_entity_type'), 'data_provenance', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_provenance_field_name'), 'data_provenance', ['field_name'], unique=False)
    op.create_index(op.f('ix_data_provenance_source_document_id'), 'data_provenance', ['source_document_id'], unique=False)
    op.create_table('financial_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('ANNUAL', 'QUARTERLY', 'HALF_YEARLY', 'TTM', name='periodtype', native_enum=False), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('reporting_standard', sa.Enum('IND_AS', 'IGAAP', 'IFRS', 'US_GAAP', name='reportingstandard', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('canonical_unit', sa.Enum('CRORES', 'LAKHS', 'MILLIONS', 'BILLIONS', 'UNITS', name='financialunit', native_enum=False), nullable=False),
    sa.Column('is_audited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'fiscal_year', 'fiscal_quarter', name='uq_company_period')
    )
    op.create_index(op.f('ix_financial_periods_company_id'), 'financial_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_periods_end_date'), 'financial_periods', ['end_date'], unique=False)
    op.create_index(op.f('ix_financial_periods_fiscal_year'), 'financial_periods', ['fiscal_year'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_company_id'), 'securities', ['company_id'], unique=False)
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_table('share_count_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('total_shares_outstanding', sa.Float(), nullable=False),
    sa.Column('face_value_inr', sa.Float(), nullable=False),
    sa.Column('paid_up_capital_inr', sa.Float(), nullable=False),
    sa.Column('treasury_shares', sa.Float(), nullable=False),
    sa.Column('promoter_holding_pct', sa.Float(), nullable=True),
    sa.Column('public_holding_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_count_histories_as_of_date'), 'share_count_histories', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_share_count_histories_company_id'), 'share_count_histories', ['company_id'], unique=False)
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.Enum('CONSOLIDATED', 'STANDALONE', name='statementtype', native_enum=False), nullable=False),
    sa.Column('property_plant_equipment', sa.Float(), nullable=False),
    sa.Column('capital_work_in_progress', sa.Float(), nullable=False),
    sa.Column('goodwill_and_intangibles', sa.Float(), nullable=False),
    sa.Column('non_current_investments', sa.Float(), nullable=False),
    sa.Column('deferred_tax_assets', sa.Float(), nullable=False),
    sa.Column('other_non_current_assets', sa.Float(), nullable=False),
    sa.Column('total_non_current_assets', sa.Float(), nullable=False),
    sa.Column('inventories', sa.Float(), nullable=False),
    sa.Column('trade_receivables', sa.Float(), nullable=False),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=False),
    sa.Column('bank_balances_other', sa.Float(), nullable=False),
    sa.Column('short_term_loans_and_advances', sa.Float(), nullable=False),
    sa.Column('other_current_assets', sa.Float(), nullable=False),
    sa.Column('total_current_assets', sa.Float(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('equity_share_capital', sa.Float(), nullable=False),
    sa.Column('other_equity_and_reserves', sa.Float(), nullable=False),
    sa.Column('non_controlling_interests', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('non_current_borrowings', sa.Float(), nullable=False),
    sa.Column('deferred_tax_liabilities', sa.Float(), nullable=False),
    sa.Column('other_non_current_liabilities', sa.Float(), nullable=False),
    sa.Column('total_non_current_liabilities', sa.Float(), nullable=False),
    sa.Column('current_borrowings', sa.Float(), nullable=False),
    sa.Column('trade_payables', sa.Float(), nullable=False),
    sa.Column('other_current_liabilities', sa.Float(), nullable=False),
    sa.Column('short_term_provisions', sa.Float(), nullable=False),
    sa.Column('total_current_liabilities', sa.Float(), nullable=False),
    sa.Column('total_liabilities', sa.Float(), nullable=False),
    sa.Column('total_equity_and_liabilities', sa.Float(), nullable=False),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'statement_type', name='uq_balance_sheet_period_type')
    )
    op.create_index(op.f('ix_balance_sheets_period_id'), 'balance_sheets', ['period_id'], unique=False)
    op.create_table('cash_flow_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.Enum('CONSOLIDATED', 'STANDALONE', name='statementtype', native_enum=False), nullable=False),
    sa.Column('cash_from_operating_activities', sa.Float(), nullable=False),
    sa.Column('cash_from_investing_activities', sa.Float(), nullable=False),
    sa.Column('cash_from_financing_activities', sa.Float(), nullable=False),
    sa.Column('net_increase_in_cash', sa.Float(), nullable=False),
    sa.Column('foreign_exchange_effect', sa.Float(), nullable=False),
    sa.Column('cash_beginning_of_period', sa.Float(), nullable=False),
    sa.Column('cash_end_of_period', sa.Float(), nullable=False),
    sa.Column('capital_expenditure', sa.Float(), nullable=False),
    sa.Column('free_cash_flow', sa.Float(), nullable=False),
    sa.Column('dividend_paid', sa.Float(), nullable=False),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'statement_type', name='uq_cash_flow_period_type')
    )
    op.create_index(op.f('ix_cash_flow_statements_period_id'), 'cash_flow_statements', ['period_id'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.Enum('CONSOLIDATED', 'STANDALONE', name='statementtype', native_enum=False), nullable=False),
    sa.Column('revenue_from_operations', sa.Float(), nullable=False),
    sa.Column('other_income', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('cost_of_materials_consumed', sa.Float(), nullable=False),
    sa.Column('purchases_of_stock_in_trade', sa.Float(), nullable=False),
    sa.Column('changes_in_inventories', sa.Float(), nullable=False),
    sa.Column('employee_benefit_expenses', sa.Float(), nullable=False),
    sa.Column('finance_costs', sa.Float(), nullable=False),
    sa.Column('depreciation_and_amortization', sa.Float(), nullable=False),
    sa.Column('other_expenses', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('operating_profit', sa.Float(), nullable=False),
    sa.Column('profit_before_exceptional_items_and_tax', sa.Float(), nullable=False),
    sa.Column('exceptional_items', sa.Float(), nullable=False),
    sa.Column('profit_before_tax', sa.Float(), nullable=False),
    sa.Column('current_tax', sa.Float(), nullable=False),
    sa.Column('deferred_tax', sa.Float(), nullable=False),
    sa.Column('total_tax_expense', sa.Float(), nullable=False),
    sa.Column('profit_after_tax', sa.Float(), nullable=False),
    sa.Column('minority_interest', sa.Float(), nullable=False),
    sa.Column('share_of_profit_associates', sa.Float(), nullable=False),
    sa.Column('net_profit_attributable_to_owners', sa.Float(), nullable=False),
    sa.Column('basic_eps', sa.Float(), nullable=True),
    sa.Column('diluted_eps', sa.Float(), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'statement_type', name='uq_income_statement_period_type')
    )
    op.create_index(op.f('ix_income_statements_period_id'), 'income_statements', ['period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_statements_period_id'), table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_cash_flow_statements_period_id'), table_name='cash_flow_statements')
    op.drop_table('cash_flow_statements')
    op.drop_index(op.f('ix_balance_sheets_period_id'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    op.drop_index(op.f('ix_share_count_histories_company_id'), table_name='share_count_histories')
    op.drop_index(op.f('ix_share_count_histories_as_of_date'), table_name='share_count_histories')
    op.drop_table('share_count_histories')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_index(op.f('ix_securities_company_id'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_financial_periods_fiscal_year'), table_name='financial_periods')
    op.drop_index(op.f('ix_financial_periods_end_date'), table_name='financial_periods')
    op.drop_index(op.f('ix_financial_periods_company_id'), table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_index(op.f('ix_data_provenance_source_document_id'), table_name='data_provenance')
    op.drop_index(op.f('ix_data_provenance_field_name'), table_name='data_provenance')
    op.drop_index(op.f('ix_data_provenance_entity_type'), table_name='data_provenance')
    op.drop_index(op.f('ix_data_provenance_entity_id'), table_name='data_provenance')
    op.drop_table('data_provenance')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_company_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_rule_name'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_period_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_entity_type'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_entity_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_company_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_category'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_cin'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
