"""create_phase_2_fundamental_analysis_tables

Revision ID: a04e686ef92a
Revises: d3664697577f
Create Date: 2026-10-03 12:19:19.346187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04e686ef92a'
down_revision: Union[str, None] = 'd3664697577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_metric_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('metric_label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('methodology_version', sa.String(length=20), nullable=False),
    sa.Column('formula_expression', sa.String(length=500), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_metric_records_category'), 'fundamental_metric_records', ['category'], unique=False)
    op.create_index(op.f('ix_fundamental_metric_records_company_id'), 'fundamental_metric_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_fundamental_metric_records_metric_key'), 'fundamental_metric_records', ['metric_key'], unique=False)
    op.create_index(op.f('ix_fundamental_metric_records_period_id'), 'fundamental_metric_records', ['period_id'], unique=False)
    op.create_index(op.f('ix_fundamental_metric_records_statement_type'), 'fundamental_metric_records', ['statement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamental_metric_records_statement_type'), table_name='fundamental_metric_records')
    op.drop_index(op.f('ix_fundamental_metric_records_period_id'), table_name='fundamental_metric_records')
    op.drop_index(op.f('ix_fundamental_metric_records_metric_key'), table_name='fundamental_metric_records')
    op.drop_index(op.f('ix_fundamental_metric_records_company_id'), table_name='fundamental_metric_records')
    op.drop_index(op.f('ix_fundamental_metric_records_category'), table_name='fundamental_metric_records')
    op.drop_table('fundamental_metric_records')
    # ### end Alembic commands ###
